config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interview.rb
class Interview < ApplicationRecord
  store_attribute :contents, :work_situation, :string                  # 勤務の状況(テキスト)
  store_attribute :contents, :fatigue_accumulation, :integer           # 疲労蓄積度(4段階 単一選択)
  store_attribute :contents, :mental_and_physical_condition, :boolean  # 心身の状況(所見あり/所見なし)
  store_attribute :contents, :guidance_kbn, :json                      # 本人への指導区分(選択方式 複数選択可)
  store_attribute :contents, :note, :string                            # その他の特記事項
  
  GUIDANCE_KBN_NAME = {
    'sochi_fuyo' => '0. 措置不要',
    'yo_hokenshido' => '1. 要保健指導',
    'yo_keikakansatsu' => '2. 要経過観察',
    'yo_saimensetsu' => '3. 要再面接',
    'chiryo' => '4. 現病治療継続 又は 医療機関紹介'
  }.freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: %i[ show edit update destroy ]

  # GET /interviews or /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1 or /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews or /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to interview_url(@interview), notice: "Interview was successfully created." }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1 or /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to interview_url(@interview), notice: "Interview was successfully updated." }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1 or /interviews/1.json
  def destroy
    @interview.destroy

    respond_to do |format|
      format.html { redirect_to interviews_url, notice: "Interview was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interview_params
      params.require(:interview).permit(:interveiw_on, :employee_name, :docter_name, :contents, :work_situation, :fatigue_accumulation,
        :mental_and_physical_condition, :note, guidance_kbn: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview) do |form| %>
  <% if interview.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
        <% interview.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-2">
    <%= form.label :interveiw_on, style: "display: block", class: 'form-label' %>
    <%= form.date_field :interveiw_on, class: 'form-control' %>
  </div>

  <div class="col-md-2">
    <%= form.label :employee_name, style: "display: block", class: 'form-label' %>
    <%= form.text_field :employee_name, class: 'form-control' %>
  </div>

  <div class="col-md-2">
    <%= form.label :docter_name, style: "display: block", class: 'form-label' %>
    <%= form.text_field :docter_name, class: 'form-control' %>
  </div>

  <div class="col-md-2">
    <%= form.label :work_situation, style: "display: block", class: 'form-label' %>
    <%= form.text_field :work_situation, class: 'form-control' %>
  </div>

  <div class="col-md-2">
    <%= form.label :fatigue_accumulation, style: "display: block", class: 'form-label' %>
    <%= form.number_field :fatigue_accumulation, { min: 0, max: 3, step: 1, class: 'form-control' } %>
  </div>

  <div class="col-md-2">
    <%= form.label :mental_and_physical_condition, style: "display: block", class: 'form-label' %>
    <div class="form-check">
      <%= form.radio_button :mental_and_physical_condition, false, class: 'form-check-input' %>
      <%= form.label :mental_and_physical_condition, '所見なし', { value: false, class: 'form-check-label' } %>
    </div>
    <div class="form-check">
      <%= form.radio_button :mental_and_physical_condition, true, class: 'form-check-input' %>
      <%= form.label :mental_and_physical_condition, '所見あり', { value: true, class: 'form-check-label' } %>
    </div>
  </div>

  <div class="col-md-3">
    <%= form.label :guidance_kbn, style: "display: block", class: 'form-label' %>
    <% form.object.class::GUIDANCE_KBN_NAME.keys.each do |guidance_kbn| %>
      <div class="form-check">
        <%= form.check_box  :guidance_kbn, { multiple: true, class: 'form-check-input' }, guidance_kbn, nil %>
        <%= form.label :guidance_kbn, form.object.class::GUIDANCE_KBN_NAME[guidance_kbn], { value: guidance_kbn, class: 'form-check-label' } %>
      </div>
    <% end %>
  </div>

  <div class="col-md-2">
    <%= form.label :note, style: "display: block", class: 'form-label' %>
    <%= form.text_field :note, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit nil, class: 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/interviews/_interview.html.erb
<div id="<%= dom_id interview %>">
  <p>
    <strong>Id:</strong>
    <%= interview.id %>
  </p>
  <p>
    <strong>Interveiw on:</strong>
    <%= interview.interveiw_on %>
  </p>

  <p>
    <strong>Employee name:</strong>
    <%= interview.employee_name %>
  </p>

  <p>
    <strong>Docter name:</strong>
    <%= interview.docter_name %>
  </p>

  <p>
    <strong>Work Situation:</strong>
    <%= interview.work_situation %>
  </p>

  <p>
    <strong>Fatigue Accumulation:</strong>
    <%= interview.fatigue_accumulation %>
  </p>
  
  <p>
    <strong>Mental And Physical Condition:</strong>
    <%= interview.mental_and_physical_condition ? '所見あり': '所見なし' %>
  </p>
  
  <p>
    <strong>Guidance Kbn:</strong>
    <%= interview.guidance_kbn.map { |guidance_kbn| Interview::GUIDANCE_KBN_NAME[guidance_kbn] }.join('、') %>
  </p>
  
  <p>
    <strong>Note:</strong>
    <%= interview.note %>
  </p>
</div>

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render "form", interview: @interview %>

<br>

<div>
  <%= link_to "Show this interview", @interview, class: 'btn btn-primary' %>
  <%= link_to "Back to interviews", interviews_path, class: 'btn btn-primary' %>
</div>

app/views/interviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Interviews</h1>

<div id="interviews">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Interview On</th>
        <th scope="col">Employee Name</th>
        <th scope="col">Doctor Name</th>
        <th scope="col">Work Situation</th>
        <th scope="col">Fatigue Accumulation</th>
        <th scope="col">Mental And Physical Condition</th>
        <th scope="col">Guidance Kbn</th>
        <th scope="col">Note</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @interviews.each do |interview| %>
        <tr id="<%= dom_id interview %>">
          <th scope="row"><%= interview.id %></th>
          <td><%= interview.interveiw_on %></td>
          <td><%= interview.employee_name %></td>
          <td><%= interview.docter_name %></td>
          <td><%= interview.work_situation %></td>
          <td><%= interview.fatigue_accumulation %></td>
          <td><%= interview.mental_and_physical_condition ? '所見あり' : '所見なし' %></td>
          <td><%= interview.guidance_kbn.map { |guidance_kbn| Interview::GUIDANCE_KBN_NAME[guidance_kbn] }.join('、') %></td>
          <td><%= interview.note %></td>
          <td><%= link_to "Show this interview", interview, class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New interview", new_interview_path, class: 'btn btn-primary' %>

app/views/interviews/new.html.erb
<h1>New interview</h1>

<%= render "form", interview: @interview %>

<br>

<div>
  <%= link_to "Back to interviews", interviews_path %>
</div>

app/views/interviews/show.html.erb
<h1>Showing interview</h1>

<p style="color: green"><%= notice %></p>

<%= render @interview %>
<div>
  <%= link_to "Edit this interview", edit_interview_path(@interview), class: 'btn btn-primary' %>
  <%= link_to "Back to interviews", interviews_path, class: 'btn btn-primary' %>

  <%= button_to "Destroy this interview", @interview, method: :delete, class: 'btn btn-danger mt-1' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreModelPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div style="width: 90vw; margin: 0 auto;">
      <%= yield %>
    </div>
  </body>
</html>